<?php
	$translations = [

		//files
		'fichtean_curve.txt' => 'fichtean_curve.txt',
		'freytags_pyramid.txt' => 'freytags_pyramid.txt',
		'heros_journey.txt' => 'heros_journey.txt',
		'story_clock.txt' => 'story_clock.txt',
		'save_the_cat.txt' => 'save_the_cat.txt',
		'dan_harmons_story_circle.txt' => 'dan_harmons_story_circle.txt',

		//index.php
		'Default Language' => 'English',
		'Default Structure' => 'fichtean_curve.txt',
		'You must be logged in to create a book.' => 'You must be logged in to create a book.',
		'Playground - The Book - Index' => 'Playground - The Book - Index',
		'Toggle Mode' => 'Dark/Light Mode',
		'Add Book' => 'Add Book',
		'AI Engines:' => 'AI Engines:',
		'Hello' => 'Hello',
		'Read More' => 'Read More',
		'Delete Book' => 'Delete Book',
		'Author:' => 'Author:',
		'Loading...' => 'Loading...',
		'describe your books story, people and events. While you can just say \'A Boy Meets World\' the longer and more detailed your blurb is the more creative and unique the writing will be.' => 'describe your books story, people and events. While you can just say \'A Boy Meets World\' the longer and more detailed your blurb is the more creative and unique the writing will be.',
		'English' => 'English',
		'Norwegian' => 'Norsk',
		'Turkish' => 'Türkçe',
		'Fichtean Curve (3 Acts, 8 Chapters)' => 'Fichtean Curve (3 Acts, 8 Chapters)',
		'Freytag\'s Pyramid (5 Acts, 9 Chapters)' => 'Freytag\'s Pyramid (5 Acts, 9 Chapters)',
		'Hero\'s Journey (3 Acts, 12 Chapters)' => 'Hero\'s Journey (3 Acts, 12 Chapters)',
		'Story Clock (4 Acts, 12 Chapters)' => 'Story Clock (4 Acts, 12 Chapters)',
		'Save The Cat (4 Acts, 15 Chapters)' => 'Save The Cat (4 Acts, 15 Chapters)',
		'Dan Harmon\'s Story Circle (8 Acts, 15 Chapters)' => 'Dan Harmon\'s Story Circle (8 Acts, 15 Chapters)',
		'After clicking the submit button, the AI will first write the book\'s title and blurb and characters. You\'ll need to confirm the characters before the AI writes the book.' => 'After clicking the submit button, the AI will first write the book\'s title and blurb and characters. You\'ll need to confirm the characters before the AI writes the book.',
		'Please verify the title, blurb the back cover text of the book and the characters of the story.' => 'Please verify the title, blurb the back cover text of the book and the characters of the story.',
		'After clicking the submit button, The AI will start creating all the chapters for the book. This process may take a few minutes.' => 'After clicking the submit button, The AI will start creating all the chapters for the book. This process may take a few minutes.',
		'Book Blurb' => 'Book Blurb',
		'Back Cover Text' => 'Back Cover Text',
		'Character Profiles' => 'Character Profiles',
		'Submit' => 'Submit',
		'Confirm Deletion' => 'Confirm Deletion',
		'Are you sure you want to delete this book? This action cannot be undone.' => 'Are you sure you want to delete this book? This action cannot be undone.',
		'Delete' => 'Delete',
		'Cancel' => 'Cancel',
		'Error deleting book:' => 'Error deleting book:',
		'Error occurred while deleting the book.' => 'Error occurred while deleting the book.',
		'Book created successfully. Please check the new fields before continuing.' => 'Book created successfully. Please check the new fields before continuing.',
		'name' => 'name',
		'Error:' => 'Error:',
		'Book created successfully.' => 'Book created successfully.',

		//login.php
		'Playground Books - Login' => 'Playground Books - Login',
		'Login / Register' => 'Login / Register',
		'username' => 'username',
		'password' => 'password',
		'Browse As Visitor' => 'Browse As Visitor',
		'You can login with any username and password. If the username doesn\'t exist, it will be created. The password will be hashed. If the username exists, the password will be verified. If the password is incorrect, you will be told so.' => 'You can login with any username and password. If the username doesn\'t exist, it will be created. The password will be hashed. If the username exists, the password will be verified. If the password is incorrect, you will be told so.',


		//book-details.php
		'Select an AI Engine' => 'Select an AI Engine',
		'Write All Beats' => 'Write All Beats',
		'Cover Image' => 'Cover Image',
		'Export as PDF' => 'Export as PDF',
		'Export as DocX' => 'Export as DocX',
		'View Book' => 'View Book',

		'Back to Books' => 'Back to Books',
		'Log out' => 'Log out',
		'Login/Sign up' => 'Login/Sign up',
		'Playground Book' => 'Playground Book',
		'About Book' => 'About Book',
		'Book Cover' => 'Book Cover',
		'Edit Chapter' => 'Edit Chapter',
		'Name' => 'Name',
		'Text' => 'Text',
		'Events' => 'Events',
		'People' => 'People',
		'Places' => 'Places',
		'Prev Chapter' => 'Prev Chapter',
		'Next Chapter' => 'Next Chapter',
		'Background Color' => 'Background Color',
		'Upload Files' => 'Upload Files',
		'Comments' => 'Comments',
		'Files' => 'Files',
		'Save Chapter' => 'Save Chapter',
		'Add Comment' => 'Add Comment',
		'View History' => 'View History',
		'Close' => 'Close',

		'Create Cover' => 'Create Cover',
		'Enter cover description' => 'Enter cover description',
		'Book Title' => 'Book Title',
		'Book Author' => 'Book Author',
		'Enhance Prompt' => 'Enhance Prompt',
		'AI will optimize for creative visuals' => 'AI will optimize for creative visuals',
		'Generate' => 'Generate',
		'Save' => 'Save',
		'Comment' => 'Comment',
		'History' => 'History',

		'Book Structure' => 'Book Structure',
		'Generating Beats for All Chapters' => 'Generating Beats for All Chapters',
		'Playground - The Book' => 'Playground - The Book',
		'Visitor' => 'Visitor',

		//chapter-beats.php
		'Playground - The Book - Beats' => 'Playground - The Book - Beats',
		'Write All Beat Contents' => 'Write All Beat Contents',
		'Recreate Beats' => 'Recreate Beats',
		'Read all beats' => 'Read all beats',
		'Back to Chapters' => 'Back to Chapters',
		'Save Beats' => 'Save Beats',
		'Description' => 'Description',
		'Previous Chapter' => 'Previous Chapter',
		'Beats' => 'Beats',
		'Writing All Beats' => 'Writing All Beats',
		'Read Chapter Beats' => 'Read Chapter Beats',


		//action-beats.php
		//action-init.php
		'You are not the owner of this book.' => 'You are not the owner of this book.',
		'This is the description for Beat 1' => 'This is the description for Beat 1',
		'This is the description for Beat 2' => 'This is the description for Beat 2',
		'This is the description for Beat 3' => 'This is the description for Beat 3',
		'Failed to generate beats' => 'Failed to generate beats',
		'Chapter file not found' => 'Chapter file not found',
		'Failed to write to file' => 'Failed to write to file',
		'Book not found.' => 'Book not found.',
		'Book JSON file not found.' => 'Book JSON file not found.',
		'must be a directory' => 'must be a directory',
		'Book directory not found' => 'Book directory not found',
		'Error decoding JSON:' => 'Error decoding JSON:',
		'Chapters JSON file not found.' => 'Chapters JSON file not found.',


		//action-book.php
		'Book created successfully' => 'Book created successfully',
		'Failed to generate book' => 'Failed to generate book',
		'Created chapter' => 'Created chapter',
		'Edited chapter' => 'Edited chapter',
		'Cover saved successfully' => 'Cover saved successfully',

		//action-make-cover.php
		'Image generated successfully' => 'Image generated successfully',
		'Error (2) generating image' => 'Error (2) generating image',
		'Error (1) generating image' => 'Error (1) generating image',

		//action-other-functions.php
		'Deleted comment' => 'Deleted comment',
		'Added comment' => 'Added comment',
		'Edited comment' => 'Edited comment',
		'Username and password are required' => 'Username and password are required',
		'Invalid username or password' => 'Invalid username or password',

		//custom-ui.js
		'Failed to load book structure: ' => 'Failed to load book structure: ',

		//beat.js
		'Blurb' => 'Blurb',
		'From Previous Chapter' => 'From Previous Chapter',
		'To Next Chapter' => 'To Next Chapter',
		'Beats:' => 'Beats:',
		'This process will write the texts and the summaries for all beats in this chapter. The summaries are used to create the next beat. Please wait... ' => 'This process will write the texts and the summaries for all beats in this chapter. The summaries are used to create the next beat. Please wait... ',
		'If the progress bar is stuck for a long time, please refresh the page and try again.' => 'If the progress bar is stuck for a long time, please refresh the page and try again.',
		'Beat ${beatIndex + 1} already has text. Skipping...' => 'Beat ${beatIndex + 1} already has text. Skipping...',
		'Writing beat ${beatIndex}' => 'Writing beat ${beatIndex}',
		'Beat Description:' => 'Beat Description:',
		'Summary for beat ${beatIndex}:' => 'Summary for beat ${beatIndex}:',
		'Error processing beat ${beatIndex}: ${error}' => 'Error processing beat ${beatIndex}: ${error}',
		'All beats processed!' => 'All beats processed!',
		'After reviewing the beats, click the "Save Beats" button to save the changes.' => 'After reviewing the beats, click the "Save Beats" button to save the changes.',
		'Beat Description' => 'Beat Description',
		'Beat Text' => 'Beat Text',
		'Beat Text Summary' => 'Beat Text Summary',
		'Save Beat' => 'Save Beat',
		'Write Beat Text' => 'Write Beat Text',
		'Write Summary' => 'Write Summary',
		'Beat' => 'Beat',
		'Failed to create beats: ' => 'Failed to create beats: ',
		'An error occurred while creating beats.' => 'An error occurred while creating beats.',
		'Writing beat text...' => 'Writing beat text...',
		'Beat text generated successfully!' => 'Beat text generated successfully!',
		'Failed to write beat text: ' => 'Failed to write beat text: ',
		'Writing beat text summary...' => 'Writing beat text summary...',
		'Beat text summary generated successfully!' => 'Beat text summary generated successfully!',
		'Failed to write summary: ' => 'Failed to write summary: ',
		'Beat saved successfully!' => 'Beat saved successfully!',
		'Failed to save beat: ' => 'Failed to save beat: ',
		'Start of the book' => 'Start of the book',
		'Beats saved successfully!' => 'Beats saved successfully!',
		'Failed to save beats: ' => 'Failed to save beats: ',
		'Are you sure you want to recreate the beats? This will overwrite any existing beats.' => 'Are you sure you want to recreate the beats? This will overwrite any existing beats.',



		//chapter.js
		'Act ${act}' => 'Act ${act}',
		'Prev' => 'Prev',
		'Next' => 'Next',
		'Open Beats' => 'Open Beats',
		'Chapter saved successfully!' => 'Chapter saved successfully!',
		'Failed to save chapter: ' => 'Failed to save chapter: ',
		'Error loading chapter:' => 'Error loading chapter:',
		'This process will write 10 short beats for each chapter in the book. Later these beats will be turned into full book pages.' => 'This process will write 10 short beats for each chapter in the book. Later these beats will be turned into full book pages.',
		'Please wait...' => 'Please wait...',
		'Processing chapter: ${chapter}' => 'Processing chapter: ${chapter}',
		'Chapter "${chapter}" already has beats. Skipping...' => 'Chapter "${chapter}" already has beats. Skipping...',
		'Beat ${index}' => 'Beat ${index}',
		'Beats generated and saved for chapter: ${chapter}' => 'Beats generated and saved for chapter: ${chapter}',
		'Beats generated but failed to save for chapter: ${chapter}' => 'Beats generated but failed to save for chapter: ${chapter}',
		'Failed to generate beats: ' => 'Failed to generate beats: ',
		'Error saving beats for chapter: ${chapter}' => 'Error saving beats for chapter: ${chapter}',
		'Failed to generate beats for chapter: ${chapter} :: ${response}' => 'Failed to generate beats for chapter: ${chapter} :: ${response}',
		'Error generating beats for chapter: ${chapter}' => 'Error generating beats for chapter: ${chapter}',
		'All chapters processed!' => 'All chapters processed!',
		'Prompt For Book:' => 'Prompt For Book:',
		'Character Profiles:' => 'Character Profiles:',
		'An image describing: ' => 'An image describing: ',
		'Generating...' => 'Generating...',
		'Failed to generate cover: ' => 'Failed to generate cover: ',
		'Cover saved successfully!' => 'Cover saved successfully!',
		'Failed to save cover: ' => 'Failed to save cover: ',


	];
