<?php
	$translations = [

		//index.php
		'Playground - The Book - Index' => 'Oyun Alanı - Kitap - Dizin',
		'Toggle Mode' => 'Karanlık/Aydınlık Modu',
		'Add Book' => 'Kitap Ekle',
		'AI Engines:' => 'Yapay Zeka Motorları:',
		'Hello' => 'Merhaba',
		'Read More' => 'Daha Fazla Oku',
		'Delete Book' => 'Kitabı Sil',
		'Author:' => 'Yazar:',
		'Loading...' => 'Yükleniyor...',
		'describe your books story, people and events. While you can just say \'A Boy Meets World\' the longer and more detailed your blurb is the more creative and unique the writing will be.' => 'kitabınızın hikayesini, kişilerini ve olaylarını anlatın. Sadece \'Bir Çocuk Dünyayla Tanışıyor\' diyebilirsiniz, ancak tanıtım yazınız ne kadar uzun ve ayrıntılı olursa, yazı o kadar yaratıcı ve özgün olacaktır.',
		'English' => 'İngilizce',
		'Norwegian' => 'Norveççe',
		'Turkish' => 'Türkçe',
		'Fichtean Curve (3 Acts, 8 Chapters)' => 'Fichtean Eğrisi (3 Perde, 8 Bölüm)',
		'Freytag\'s Pyramid (5 Acts, 9 Chapters)' => 'Freytag\'ın Piramidi (5 Perde, 9 Bölüm)',
		'Hero\'s Journey (3 Acts, 12 Chapters)' => 'Kahramanın Yolculuğu (3 Perde, 12 Bölüm)',
		'Story Clock (4 Acts, 12 Chapters)' => 'Hikaye Saati (4 Perde, 12 Bölüm)',
		'Save The Cat (4 Acts, 15 Chapters)' => 'Kediyi Kurtar (4 Perde, 15 Bölüm)',
		'Dan Harmon\'s Story Circle (8 Acts, 15 Chapters)' => 'Dan Harmon\'un Hikaye Çemberi (8 Perde, 15 Bölüm)',
		'After clicking the submit button, the AI will first write the book\'s title and blurb and characters. You\'ll need to confirm the characters before the AI writes the book.' => 'Gönder düğmesine tıkladıktan sonra, yapay zeka önce kitabın başlığını, tanıtım yazısını ve karakterlerini yazacak. Yapay zeka kitabı yazmadan önce karakterleri onaylamanız gerekecek.',
		'Please verify the title, blurb the back cover text of the book and the characters of the story.' => 'Lütfen başlığı, kitabın arka kapak metnini ve hikayenin karakterlerini doğrulayın.',
		'After clicking the submit button, The AI will start creating all the chapters for the book. This process may take a few minutes.' => 'Gönder düğmesine tıkladıktan sonra, yapay zeka kitabın tüm bölümlerini oluşturmaya başlayacak. Bu işlem birkaç dakika sürebilir.',
		'Book Blurb' => 'Kitap Tanıtımı',
		'Back Cover Text' => 'Arka Kapak Metni',
		'Character Profiles' => 'Karakter Profilleri',
		'Submit' => 'Gönder',
		'Confirm Deletion' => 'Silmeyi Onayla',
		'Are you sure you want to delete this book? This action cannot be undone.' => 'Bu kitabı silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.',
		'Delete' => 'Sil',
		'Cancel' => 'İptal',
		'Error deleting book:' => 'Kitap silinirken hata oluştu:',
		'Error occurred while deleting the book.' => 'Kitap silinirken bir hata oluştu.',
		'Book created successfully. Please check the new fields before continuing.' => 'Kitap başarıyla oluşturuldu. Devam etmeden önce lütfen yeni alanları kontrol edin.',
		'name' => 'isim',
		'Error:' => 'Hata:',
		'Book created successfully.' => 'Kitap başarıyla oluşturuldu.',

		//login.php
		'Playground Books - Login' => 'Playground Books - Giriş',
		'Login / Register' => 'Giriş / Kayıt Ol',
		'username' => 'kullanıcı adı',
		'password' => 'şifre',
		'Browse As Visitor' => 'Ziyaretçi Olarak Gez',
		'You can login with any username and password. If the username doesn\'t exist, it will be created. The password will be hashed. If the username exists, the password will be verified. If the password is incorrect, you will be told so.' => 'Herhangi bir kullanıcı adı ve şifre ile giriş yapabilirsiniz. Kullanıcı adı mevcut değilse, oluşturulacaktır. Şifre şifrelenecektir. Kullanıcı adı mevcutsa, şifre doğrulanacaktır. Şifre yanlışsa, size bildirilecektir.',


		//book-details.php
		'Select an AI Engine' => 'Bir YZ Motoru Seçin',
		'Write All Beats' => 'Tüm Vuruşları Yaz',
		'Cover Image' => 'Kapak Resmi',
		'Export as PDF' => 'PDF Olarak Dışa Aktar',
		'Export as DocX' => 'DocX Olarak Dışa Aktar',
		'View Book' => 'Kitabı Görüntüle',

		'Back to Books' => 'Kitaplara Geri Dön',
		'Log out' => 'Çıkış Yap',
		'Login/Sign up' => 'Giriş Yap/Kaydol',
		'Playground Book' => 'Playground Kitabı',
		'About Book' => 'Kitap Hakkında',
		'Book Cover' => 'Kitap Kapağı',
		'Edit Chapter' => 'Bölümü Düzenle',
		'Name' => 'İsim',
		'Text' => 'Metin',
		'Events' => 'Olaylar',
		'People' => 'İnsanlar',
		'Places' => 'Yerler',
		'Prev Chapter' => 'Önceki Bölüm',
		'Next Chapter' => 'Sonraki Bölüm',
		'Background Color' => 'Arka Plan Rengi',
		'Upload Files' => 'Dosya Yükle',
		'Comments' => 'Yorumlar',
		'Files' => 'Dosyalar',
		'Save Chapter' => 'Bölümü Kaydet',
		'Add Comment' => 'Yorum Ekle',
		'View History' => 'Geçmişi Görüntüle',
		'Close' => 'Kapat',

		'Create Cover' => 'Kapak Oluştur',
		'Enter cover description' => 'Kapak açıklamasını girin',
		'Book Title' => 'Kitap Başlığı',
		'Book Author' => 'Kitap Yazarı',
		'Enhance Prompt' => 'Komutu Geliştir',
		'AI will optimize for creative visuals' => 'YZ yaratıcı görseller için optimize edecek',
		'Generate' => 'Oluştur',
		'Save' => 'Kaydet',
		'Comment' => 'Yorum',
		'History' => 'Geçmiş',

		'Book Structure' => 'Kitap Yapısı',
		'Generating Beats for All Chapters' => 'Tüm Bölümler İçin Vuruşlar Oluşturuluyor',
		'Playground - The Book' => 'Playground - Kitap',
		'Visitor' => 'Ziyaretçi',

		//chapter-beats.php
		'Playground - The Book - Beats' => 'Oyun Alanı - Kitap - Vuruşlar',
		'Write All Beat Contents' => 'Tüm Vuruş İçeriklerini Yaz',
		'Recreate Beats' => 'Vuruşları Yeniden Oluştur',
		'Read all beats' => 'Tüm vuruşları oku',
		'Back to Chapters' => 'Bölümlere Geri Dön',
		'Save Beats' => 'Vuruşları Kaydet',
		'Description' => 'Açıklama',
		'Previous Chapter' => 'Önceki Bölüm',
		'Beats' => 'Vuruşlar',
		'Writing All Beats' => 'Tüm Vuruşları Yazma',
		'Read Chapter Beats' => 'Bölüm Vuruşlarını Oku',


		//action-beats.php
		//action-init.php
		'You are not the owner of this book.' => 'Bu kitabın sahibi siz değilsiniz.',
		'This is the description for Beat 1' => 'Bu, Vuruş 1 için açıklamadır',
		'This is the description for Beat 2' => 'Bu, Vuruş 2 için açıklamadır',
		'This is the description for Beat 3' => 'Bu, Vuruş 3 için açıklamadır',
		'Failed to generate beats' => 'Vuruşlar oluşturulamadı',
		'Chapter file not found' => 'Bölüm dosyası bulunamadı',
		'Failed to write to file' => 'Dosyaya yazılamadı',
		'Book not found.' => 'Kitap bulunamadı.',
		'Book JSON file not found.' => 'Kitap JSON dosyası bulunamadı.',
		'must be a directory' => 'bir dizin olmalı',
		'Book directory not found' => 'Kitap dizini bulunamadı',
		'Error decoding JSON:' => 'JSON çözümlenirken hata oluştu:',
		'Chapters JSON file not found.' => 'Bölümler JSON dosyası bulunamadı.',


		//action-book.php
		'Book created successfully' => 'Kitap başarıyla oluşturuldu',
		'Failed to generate book' => 'Kitap oluşturulamadı',
		'Created chapter' => 'Bölüm oluşturuldu',
		'Edited chapter' => 'Bölüm düzenlendi',
		'Cover saved successfully' => 'Kapak başarıyla kaydedildi',

		//action-make-cover.php
		'Image generated successfully' => 'Görsel başarıyla oluşturuldu',
		'Error (2) generating image' => 'Görsel oluşturulurken hata (2) oluştu',
		'Error (1) generating image' => 'Görsel oluşturulurken hata (1) oluştu',

		//action-other-functions.php
		'Deleted comment' => 'Yorum silindi',
		'Added comment' => 'Yorum eklendi',
		'Edited comment' => 'Yorum düzenlendi',
		'Username and password are required' => 'Kullanıcı adı ve şifre gereklidir',
		'Invalid username or password' => 'Geçersiz kullanıcı adı veya şifre',

		//custom-ui.js
		'Failed to load book structure: ' => 'Kitap yapısı yüklenemedi: ',

		//beat.js
		'Blurb' => 'Tanıtım',
		'From Previous Chapter' => 'Önceki Bölümden',
		'To Next Chapter' => 'Sonraki Bölüme',
		'Beats:' => 'Vuruşlar:',
		'This process will write the texts and the summaries for all beats in this chapter. The summaries are used to create the next beat. Please wait... ' => 'Bu işlem, bu bölümdeki tüm vuruşlar için metinleri ve özetleri yazacaktır. Özetler bir sonraki vuruşu oluşturmak için kullanılır. Lütfen bekleyin...',
		'If the progress bar is stuck for a long time, please refresh the page and try again.' => 'İlerleme çubuğu uzun süre takılı kalırsa, lütfen sayfayı yenileyin ve tekrar deneyin.',
		'Beat ${beatIndex + 1} already has text. Skipping...' => 'Vuruş ${beatIndex + 1} zaten metne sahip. Atlanıyor...',
		'Writing beat ${beatIndex}' => 'Vuruş ${beatIndex} yazılıyor',
		'Beat Description:' => 'Vuruş Açıklaması:',
		'Summary for beat ${beatIndex}:' => 'Vuruş ${beatIndex} için özet:',
		'Error processing beat ${beatIndex}: ${error}' => 'Vuruş ${beatIndex} işlenirken hata oluştu: ${error}',
		'All beats processed!' => 'Tüm vuruşlar işlendi!',
		'After reviewing the beats, click the "Save Beats" button to save the changes.' => 'Vuruşları gözden geçirdikten sonra, değişiklikleri kaydetmek için "Vuruşları Kaydet" düğmesine tıklayın.',
		'Beat Description' => 'Vuruş Açıklaması',
		'Beat Text' => 'Vuruş Metni',
		'Beat Text Summary' => 'Vuruş Metni Özeti',
		'Save Beat' => 'Vuruşu Kaydet',
		'Write Beat Text' => 'Vuruş Metni Yaz',
		'Write Summary' => 'Özet Yaz',
		'Beat' => 'Vuruş',
		'Failed to create beats: ' => 'Vuruşlar oluşturulamadı: ',
		'An error occurred while creating beats.' => 'Vuruşlar oluşturulurken bir hata oluştu.',
		'Writing beat text...' => 'Vuruş metni yazılıyor...',
		'Beat text generated successfully!' => 'Vuruş metni başarıyla oluşturuldu!',
		'Failed to write beat text: ' => 'Vuruş metni yazılamadı: ',
		'Writing beat text summary...' => 'Vuruş metni özeti yazılıyor...',
		'Beat text summary generated successfully!' => 'Vuruş metni özeti başarıyla oluşturuldu!',
		'Failed to write summary: ' => 'Özet yazılamadı: ',
		'Beat saved successfully!' => 'Vuruş başarıyla kaydedildi!',
		'Failed to save beat: ' => 'Vuruş kaydedilemedi: ',
		'Start of the book' => 'Kitabın başlangıcı',
		'Beats saved successfully!' => 'Vuruşlar başarıyla kaydedildi!',
		'Failed to save beats: ' => 'Vuruşlar kaydedilemedi: ',
		'Are you sure you want to recreate the beats? This will overwrite any existing beats.' => 'Vuruşları yeniden oluşturmak istediğinizden emin misiniz? Bu, mevcut vuruşların üzerine yazacaktır.',



		//chapter.js
		'Act ${act}' => 'Perde ${act}',
		'Prev' => 'Önceki',
		'Next' => 'Sonraki',
		'Open Beats' => 'Vuruşları Aç',
		'Chapter saved successfully!' => 'Bölüm başarıyla kaydedildi!',
		'Failed to save chapter: ' => 'Bölüm kaydedilemedi: ',
		'Error loading chapter:' => 'Bölüm yüklenirken hata oluştu:',
		'This process will write 10 short beats for each chapter in the book. Later these beats will be turned into full book pages.' => 'Bu işlem, kitaptaki her bölüm için 10 kısa vuruş yazacaktır. Daha sonra bu vuruşlar tam kitap sayfalarına dönüştürülecektir.',
		'Please wait...' => 'Lütfen bekleyin...',
		'Processing chapter: ${chapter}' => 'Bölüm işleniyor: ${chapter}',
		'Chapter "${chapter}" already has beats. Skipping...' => 'Bölüm "${chapter}" zaten vuruşlara sahip. Atlanıyor...',
		'Beat ${index}' => 'Vuruş ${index}',
		'Beats generated and saved for chapter: ${chapter}' => 'Bölüm için vuruşlar oluşturuldu ve kaydedildi: ${chapter}',
		'Beats generated but failed to save for chapter: ${chapter}' => 'Vuruşlar oluşturuldu ancak bölüm için kaydedilemedi: ${chapter}',
		'Failed to generate beats: ' => 'Vuruşlar oluşturulamadı: ',
		'Error saving beats for chapter: ${chapter}' => 'Bölüm için vuruşlar kaydedilirken hata oluştu: ${chapter}',
		'Failed to generate beats for chapter: ${chapter} :: ${response}' => 'Bölüm için vuruşlar oluşturulamadı: ${chapter} :: ${response}',
		'Error generating beats for chapter: ${chapter}' => 'Bölüm için vuruşlar oluşturulurken hata oluştu: ${chapter}',
		'All chapters processed!' => 'Tüm bölümler işlendi!',
		'Prompt For Book:' => 'Kitap İçin İstem:',
		'Character Profiles:' => 'Karakter Profilleri:',
		'An image describing: ' => 'Şunu tanımlayan bir görsel: ',
		'Generating...' => 'Oluşturuluyor...',
		'Failed to generate cover: ' => 'Kapak oluşturulamadı: ',
		'Cover saved successfully!' => 'Kapak başarıyla kaydedildi!',
		'Failed to save cover: ' => 'Kapak kaydedilemedi: ',


	];
